### ISSUE TITLE
Converting the tex-fast-recompile Python module into a standalone executable file

### ISSUE THREAD

**Issue by SrikanthMohankumar** [user202729/tex-fast-recompile#19]
Hello,

I have a question about converting the tex-fast-recompile Python module into a standalone executable file. Can you provide some guidance on how to do this?

Thank you!

**Comment by user202729** [comment]
I have no idea. Maybe look into `pyinstaller`?

**Comment by SrikanthMohankumar** [comment]
Sure. Thanks.
