### ISSUE TITLE
Error while using tex-fast-recompiler

### ISSUE THREAD

**Issue by Srikanth-Mohankumar** [user202729/tex-fast-recompile#21]
Hello,

While using tex-fast-recompiler, I’m receiving an error message on another machine. Could you please help me resolve this issue? Installation had no problem.

Error message:
```
SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Python\Scripts\tex_fast_recompile.exe on line 1, but no encoding declared; see https://peps.python.org/pep-0263/ for details
Process exited with error(s)
```

Thanks

**Comment by user202729** [comment]
Probably same mistake as `https://github.com/pyinstaller/pyinstaller/issues/1800`.

**Comment by Srikanth-Mohankumar** [comment]
Yes, same mistake. Thanks
