### ISSUE TITLE
Rerunfilecheck

### ISSUE THREAD

**Issue by user202729** [user202729/tex-fast-recompile#5]

**Comment by Enivex** [comment]
Is this related to this?

> but it does not do multiple compilation passes or invoke bibliography/indexing commands etc., and the simulation might not be complete

I'm excited to try this out with Latex Workshop (vscode), but presumably it's not very mature yet.

By the way: Would it be possible to cache and reuse the result from the compilation of the preamble as long as it doesn't change?

**Comment by user202729** [comment]
Personally speaking, the package works fine for me (I use vimtex). So unless something goes wrong I'll be unlikely to develop too much.

Last question: on pdftex, "mostly possible", see `mylatexformat` package (you need to be familiar with using the command-line and the documentation is slightly confusing because it's written for Windows). Other engines, a bit difficult.

**Comment by Enivex** [comment]
Do I understand correctly that it would then recompile as many times as needed to resolve references etc?

**Comment by user202729** [comment]
That's the plan (it makes sense right?) but I don't personally need that feature (just suppress warnings for draft builds). So I just leave the issue here.

**Comment by user202729** [comment]
Fixed in d5f8b0f (just grep for `Rerun to get` in log file).
